version: "3"
services:
    db:
        image: mysql:latest
        container_name: evereview-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: "evereview"
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --skip-character-set-client-handshake
            - --secure-file-priv=/app/sql_data
        volumes:
            - ./docker-mysql-dir:/var/lib/mysql
            - ./backend/sql_data:/app/sql_data
    backend:
        build:
            context: ./backend
        depends_on:
            - db
        environment:
            DB_USER: "root"
            DB_HOST: "db"
            DB_PASSWORD: ""
            DB_NAME: "evereview"
        ports:
            - "5000:5000"
